git config --global alias.s "status"
git config --global alias.amend "commit --amend --no-edit"
git config --global alias.tmp "commit -m 'Fly me to the moon'"
git config --global alias.l "log --oneline -n 10"
git config --global alias.p "push origin HEAD"
git config --global alias.pf "push origin HEAD --force-with-lease"
git config --global alias.q "checkout"
git config --global alias.cp "cherry-pick"
git config --global alias.b "branch"